version: "3"

services:

  # Create container for backend api
  backend:
    image: backend-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: "backend-api"
    volumes:
        - ./backend:/app
    ports:
      - "5000:5000"

  # Create container for frontend app
  frontend:
    image: frontend-react
    tty: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: "frontend-react"
    volumes:
        - ./frontend/src:/app/src
        - ./frontend/public:/app/public
    ports:
      - "3000:3000"